---
- name: Add modules for calico on Raspberry Pis
  hosts: raspberry_pi
  become: true
  tasks:
  - name: apt install linux-modules-extra-raspi
    ansible.builtin.apt:
      update_cache: true
      upgrade: true